### ISSUE TITLE
Broken link in installation instructions (home page)

### ISSUE THREAD

**Issue by montoyah** [metahcr/metahcr_v1#1]
Broken link: 

"Adjust Django settings.py file
You must modify the Django settings.py file to reflect the password that you have chosen for the metahcradmin user. The file is located here. Change the PASSWORD value in the DATABASES variable to metahcradmin's password. Save the settings.py file."

"here" leads to "https://github.com/metahcr/metahcr_v1.0/metahcr/metahcr/settings.py" but the file is not there.

Thanks!

Oscar Montoya

**Comment by pcmarks** [comment]
This has been fixed via Pull Request #4
