### ISSUE TITLE
Public database file not found on git LFS server

### ISSUE THREAD

**Issue by brigriffin** [metahcr/metahcr_v1#2]
Hello,

I would like to download the project including the public version of the MetaHCR database but unfortunately it seems that the database backup file does not exist on the git LFS server. Below is the output of a  `git lfs clone`.

```
$ git lfs clone git@github.com:metahcr/metahcr_v1.git
Cloning into 'metahcr_v1'...
remote: Enumerating objects: 722, done.
remote: Total 722 (delta 0), reused 0 (delta 0), pack-reused 722
Receiving objects: 100% (722/722), 5.19 MiB | 4.83 MiB/s, done.
Resolving deltas: 100% (168/168), done.
[e51973462737d3727dd0a854026f714872113b4a0b32071442567855a477fba8] Object does not exist on the server: [404] Object does not exist on the server                                                                  
error: failed to fetch some objects from 'https://github.com/metahcr/metahcr_v1.git/info/lfs'
```

I am using git LFS version `git-lfs/2.5.2 (GitHub; linux amd64; go 1.10.3)`.

Thanks in advance for checking.

**Comment by pcmarks** [comment]
Thanks for spotting this. 
git lfs clone should work now.

Please let me know if this works.

**Comment by brigriffin** [comment]
Thank you, I can now confirm that it works and was able to download the public database file :+1:
